# Generated by Django 4.2.3 on 2023-12-26 19:17

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_pages", "0003_remove_metadata_snapshot_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="page",
            name="snapshot_update",
        ),
        migrations.AddField(
            model_name="page",
            name="body_en",
            field=models.TextField(null=True, verbose_name="body"),
        ),
        migrations.AddField(
            model_name="page",
            name="title_en",
            field=models.CharField(max_length=255, null=True, verbose_name="title"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="page",
            trigger=pgtrigger.compiler.Trigger(
                name="snapshot_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."created" IS DISTINCT FROM (NEW."created") OR OLD."modified" IS DISTINCT FROM (NEW."modified") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."title" IS DISTINCT FROM (NEW."title") OR OLD."body" IS DISTINCT FROM (NEW."body"))',
                    func='INSERT INTO "baseapp_pages_pageevent" ("body", "created", "id", "modified", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "pgh_operation", "title", "user_id") VALUES (NEW."body", NEW."created", NEW."id", NEW."modified", _pgh_attach_context(), NOW(), \'snapshot\', NEW."id", 2, NEW."title", NEW."user_id"); RETURN NULL;',
                    hash="b8bd9091cc17e44a6fe82d106ffe009151f201bc",
                    operation="UPDATE",
                    pgid="pgtrigger_snapshot_update_845c1",
                    table="baseapp_pages_page",
                    when="AFTER",
                ),
            ),
        ),
    ]
