# Generated by Django 4.2.3 on 2023-12-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp_pages", "0004_remove_page_snapshot_update_page_body_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="body_es",
            field=models.TextField(null=True, verbose_name="body"),
        ),
        migrations.AddField(
            model_name="page",
            name="body_pt",
            field=models.TextField(null=True, verbose_name="body"),
        ),
        migrations.AddField(
            model_name="page",
            name="title_es",
            field=models.CharField(max_length=255, null=True, verbose_name="title"),
        ),
        migrations.AddField(
            model_name="page",
            name="title_pt",
            field=models.CharField(max_length=255, null=True, verbose_name="title"),
        ),
        migrations.AlterField(
            model_name="metadata",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("es", "Spanish"), ("pt", "Portuguese")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metadataevent",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("es", "Spanish"), ("pt", "Portuguese")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="urlpath",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[("en", "English"), ("es", "Spanish"), ("pt", "Portuguese")],
                max_length=10,
                null=True,
            ),
        ),
    ]
